title: CS4ALL
description: CS4ALL is DIKU's community for women and other gender minorities in computer science.
exclude:
  - tests/
  - docs/

# # TODO: Need to figure out how to make this work
# source: docs/
# # Plugin used to build from docs folder, but point to theme in root directory
# plugins: [jekyll-remote-theme]
# remote_theme: /srv/jekyll/

# Theme settings
site_author: Department of Computer Science, University of Copenhagen
sticky_navigation: true
prev_next_buttons_location: none
search_enabled: false
# hljs_style: atom-one-dark
hljs_languages: [ruby, python, javascript, bash, yaml]
